---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse
- src: git@github.com:ivanmanokhin/vector-role
  scm: git
  version: "1.0.1"
  name: vector
- src: git@github.com:ivanmanokhin/lighthouse-role
  scm: git
  version: "1.0.1"
  name: lighthouse
